name: CI
on:
  push:
    branches:
    - main
  pull_request_target:
  workflow_dispatch:
jobs:
  ci:
    uses: ./.github/workflows/main.yml
    with:
      publish: ${{ github.event_name == 'push' && github.server_url == 'https://github.com' }}
      use-repo-files: true
    secrets: inherit