name: CI
on: [push]
jobs:
  buildangle:
    runs-on: macos-latest
    steps:
    - name: build angle
      run: |
        export MACOSX_DEPLOYMENT_TARGET="10.10.0"
        git clone -b angle-vulkan https://github.com/ChristopherHX/moltenvk-angle Urho3D
        pushd Urho3D/Source/ThirdParty/angle
        cmake -B build .
        cmake --build build --parallel 4
        popd
    - uses: actions/upload-artifact@v3
      with:
        name: angle
        path: Urho3D/Source/ThirdParty/angle/build

    
